# Generated by Django 4.1.5 on 2023-01-22 16:07

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_connect', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to=main_page.models.Exchanges.get_file_name)),
                ('position', models.SmallIntegerField()),
            ],
        ),
    ]
