# Generated by Django 4.1.5 on 2023-02-07 20:13

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_connect', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to=main_page.models.Exchanges.get_file_name)),
                ('position', models.SmallIntegerField()),
                ('ping', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AddApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250, unique=True)),
                ('secret_api_key', models.CharField(max_length=250, unique=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.exchanges')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
