# Generated by Django 4.1.5 on 2023-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_addapikey_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addapikey',
            name='api_key',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='addapikey',
            name='secret_api_key',
            field=models.CharField(max_length=250),
        ),
    ]
