# Generated by Django 4.1.5 on 2023-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_exchanges_options_exchanges_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='ping',
            field=models.PositiveIntegerField(default='null'),
        ),
    ]
