# Generated by Django 4.1.5 on 2023-01-30 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_alter_exchanges_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='ping',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AddApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250, unique=True)),
                ('secret_api_key', models.CharField(max_length=250, unique=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.exchanges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
