# Generated by Django 4.1.7 on 2023-03-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_alter_addapikey_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEMO_Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bunch', models.JSONField()),
                ('trade', models.JSONField()),
                ('profit', models.DecimalField(decimal_places=6, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
