# Generated by Django 4.1.7 on 2023-03-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_demo_trades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo_trades',
            old_name='data',
            new_name='date',
        ),
    ]
